name: format

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          clang-format -i src/*.cpp
          clang-format -i include/*.h
          clang-format -i tests/cpp/*.cpp
