name: format

on:
  push:
    branches: [ main ]

permissions:
  pull-requests: write

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          clang-format -i src/*.cpp
          clang-format -i include/*.h
          clang-format -i tests/cpp/*.cpp

      - name: Check for changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Create new branch and commit changes
        if: ${{ env.changed }} == 'true'
        run: |
          BRANCH_NAME=auto/clang-format
          git checkout -b $BRANCH_NAME || git checkout $BRANCH_NAME
          git commit -m "Apply clang-format"
          git push -u origin $BRANCH_NAME

      - name: Create pull request
        if: ${{ changed }} == 'true'
        uses: peter-evans/create-pull-request@v6
