name: Lint code

on:
  workflow_call:
    inputs:
      description: The language to run the linter for
        required: true
        type: string
      branch:
        description: The branch to lint
        required: true
        type: string
jobs:
  lint-code:
    runs-on: ubuntu-latest

    steps:
      - Code checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}

      - Install linter [C++]
        if: ${{ inputs.language == cpp}}
        run: sudo apt-get update && sudo apt-get install -y clang-tidy

      - Run linter [C++]
        if: ${{ inputs.language == cpp }}
        run: clang-tidy src/*.cpp tests/cpp/*.cpp
        
