on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main ]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: clang-format --dry-run --Werror src/*.cpp include/*.h tests/cpp/*.cpp
